### ISSUE TITLE
split tunneling?

### ISSUE THREAD

**Issue by opnslm** [jedisct1/dsvpn#100]
So i need to tunnel dsvpn over tls. I set up stunnel(it is a tls tunneler to who dont know) everything works fine i can comminucate with the vps. But if i run dsvpn under stunnel it tries to tunnel all the traffic and interrupts the stunnel traffic. Is there a split tunneling method(i am on linuz btw) maybe like while the vpn is setting up the tun interface change some routing settings or not tunneling an ip address at all. thank you!

**Comment by jedisct1** [comment]
There's an undocumented option to prevent `dsvpn` from setting routes. Add `-DNO_DEFAULT_ROUTES` to the `OPTFLAGS` environment variable.

It will then create the `tun` interface for you but you'll have to set up all th routes yourself.

What are the exact commands you need to type for your use case, I don't know. You probably know Linux way better than I do :)

**Comment by opnslm** [comment]
How can i use the environment variable method do i put it in makefile. I don't know c that much. Where can i find the routes that is being added while the tun interface set. Thaks for the compliment;)

**Comment by opnslm** [comment]
okay i found the way to disable route it is in 98 issue(https://github.com/jedisct1/dsvpn/issues/98) and the routes for tun interface i think is on line 485 in os.c am i correct
