### ISSUE TITLE
Early users: something to try

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/dsvpn#11]
Hi early users :)

If you have some minutes to spare, could you try something?

In `src/charm.c`, just for the test, change

```c
#define ROUNDS 12
```

to

```c
#define ROUNDS 1
```

Now, in  `include/dsvpn.h`, try to change

```c
#define BUFFERBLOAT_CONTROL 0
```

to

```c
#define BUFFERBLOAT_CONTROL 1
```

And report which setting give you better speed and/or latency.

You can also try to tweak `NOTSENT_LOWAT` and `DEFAULT_MTU` a little bit.

Results may vary a lot according to what kind of connection you have.

**Comment by jedisct1** [comment]
PS: ideally, the settings should be the same on the client and on the server, so you have to recompile both after a change.

**Comment by Fastidious** [comment]
I shall try it! Heading home to play. ☺️

**Comment by Fastidious** [comment]
OK, here are my numbers:
```
87Mbps BUFFERBLOAT_CONTROL 0
85Mbps BUFFERBLOAT_CONTROL 1
110Mbps NO DSVPN
```
Haven't played with the other settings.
