### ISSUE TITLE
Add a way to find version

### ISSUE THREAD

**Issue by Fastidious** [jedisct1/dsvpn#12]
Could it be possible to add a `version` or simply `v`?

**Comment by jedisct1** [comment]
There are no versions.

**Comment by Fastidious** [comment]
> There are no versions.

[Arguably](https://github.com/jedisct1/dsvpn/issues/8#issuecomment-513285643) 🙈. Having a number (commit, maybe?) to refer to can be useful to troubleshoot.

**Comment by Fastidious** [comment]
@jedisct1 thank you for adding this.

**Comment by jedisct1** [comment]
I will probably tag a release soon.

Automatically setting the local DNS resolver will require an incompatible change to the protocol, so it makes sense to have a release before this happens.
