### ISSUE TITLE
OpenWrt package

### ISSUE THREAD

**Issue by roger-** [jedisct1/dsvpn#13]
Would be nice to have a package (requires a PR [here](https://github.com/openwrt/packages)).

**Comment by jedisct1** [comment]
Do you think you could do it? I don't have any experience with making OpenWrt packages.

**Comment by roger-** [comment]
Sure, I'll try to take a stab when I have time (it's not too hard).

**Comment by Vaelatern** [comment]
This would be easier for other people to package if it were released.
Is that reasonable for this software at this time? A 0.1.0 release?

**Comment by jedisct1** [comment]
[OpenMPTCProuter](https://github.com/Ysurac/openmptcprouter-feeds) seems to have added support for `dsvpn`, including its integration in LUCI.

But I don't know what it would take to a make a plain OpenWrt package from this.

**Comment by roger-** [comment]
Nice find! It should work as-is, you just need to build the package with the OpenWrt SDK. 

If the author wants to submit it to the official packages feed then it'd be even easier.

**Comment by jedisct1** [comment]
Cc @ysurac

**Comment by jayanta525** [comment]
Using dsvpn on openwrt, 

`iptables v1.8.4 (legacy): Couldn't load match `addrtype':No such file or directory`

**Comment by jayanta525** [comment]
Solved with ip-full.

**Comment by vochong** [comment]
> roger



> Sure, I'll try to take a stab when I have time (it's not too hard).

Hi Roger,

Could you please build an OpenWrt package for DSVPN.  Thanks a lot.
