### ISSUE TITLE
Handle firewall cleanup

### ISSUE THREAD

**Issue by angristan** [jedisct1/dsvpn#2]
I noticed that when exiting the VPN, the firewall rules and routing modifications aren't removed.

I wanted to make a PR for this, my idea was to catch `SIGINT` with `signal()` and then call a `del_firewall_rules()` function. However I'd need to pass a pointer to `context` to this function and I can't to this with `signal` (unless the variable is global).

I'm not very experienced with C so I guess you will know how to do it properly!

**Comment by angristan** [comment]
I see [you're already thinking about it](https://github.com/jedisct1/dsvpn/commit/d60984c717e898eeacc27229ed9c76528e6eeb51) 😄

**Comment by jedisct1** [comment]
Set a global to `1` in the signal handler, and in the event loop, just check if that global has been set. If this is the case, call the exit handler.
