### ISSUE TITLE
How do you like shadowsocks-libev?

### ISSUE THREAD

**Issue by nalzok** [jedisct1/dsvpn#23]
What's the differences between dsvpn and [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)? It works over TCP, doesn't require a lot of configuration, and is "for embedded devices and low-end boxes".

I'm asking this because I'm considering replacing shadowsocks with dsvpn. Yeah I know you provide no guarantees, but its minimalistic design really got me, and a smaller code base generally means more hackability. In case it's relevant, I use ss to bypass the censorship of GFW, and ss is the go-to choice for most people for this purpose.

**Comment by jedisct1** [comment]
Shadowsocks is very nice! And if you are happy with it, there are no reasons to switch.

Like `sshuttle`, one reason I wouldn't use it is that it can only tunnel TCP on non-Linux systems. And even on Linux, it looks like additional firewall rules for transparent proxying need to be installed.

dsvpn always redirects everything to the tunnel, including non-UDP and non-TCP protocols; there can be no leaks.

Also, sometimes you only want obfuscation, not encryption; you just want the VPN to be fast. Alternatively, you might have a lot of spare CPU and are very paranoid. This can easily be tuned in dsvpn just by changing the `ROUNDS` constant in `include/charm.h`.
