### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by beanz** [jedisct1/dsvpn#24]
https://github.com/jedisct1/dsvpn/blob/master/src/vpn.c#L505:

    return -1;
    memset(key, 0, sizeof key);

looks wrong to me.

**Comment by dnwe** [comment]
Sadly modern gcc no longer does unreachable code detection. Clang does pick this one up though:

```
# clang -Wunreachable-code -Wall -Wextra -Iinclude -o dsvpn src/vpn.c src/charm.c src/os.c
src/vpn.c:505:9: warning: code will never be executed [-Wunreachable-code]
        memset(key, 0, sizeof key);
        ^~~~~~
1 warning generated.
```

**Comment by jedisct1** [comment]
Good catch, that was useless, leftover code. It has been removed, thanks!
