### ISSUE TITLE
connect two clients through a public server

### ISSUE THREAD

**Issue by microspino** [jedisct1/dsvpn#25]
Hi many thx for this i'm using dsvpn at work and it's soo easy to setup that i'd like to use it anywhere. :)
I wonder which are the steps I have to take in order to do this:

- client A (at home) connects to public server Z (hosted at for ex. scaleway)
- client B (at sea house) connects to public server Z (as above)
... missing steps ...
- client A and  B can "see" each other.

I want to send small messages (mqtt which i know how to setup) between A to B
Is it possible?

I don't want to waste your time, if this is out of scope or totally lame feel free to close this issue.

**Comment by jedisct1** [comment]
Hi,

All it may take to have this working is having all the tunnel IPs within the same subnet, which is a /24 (for example `A` is `192.168.192.1`, `B` is `192.168.192.2` and `Z` is `192.168.192.254`).

My knowledge of routing in Linux is pretty limited, so maybe this also requires a bridge between the `tun*` interface.

Give it a try :)

**Comment by Fastidious** [comment]
@jedisct1 isn't this one of the "maybe" future feature?
> Support for multiple clients.

If multiple clients can connect to the same `dsvpn` server, they could—hypothetically—be able to talk to each other, no?

**Comment by jedisct1** [comment]
They won't be able to connect to the same server. They will need to connect to different ports, especially since they will be using different keys.

But if they use the same subnets, they should be able to communicate.

**Comment by microspino** [comment]
Small 👍  successful 👍  UPDATE:
First I opened two ports on the server (which is an ARM machine hosted on scaleway running Ubuntu Xenial (16.04 LTS):
```
sudo ufw allow 1959/tcp
sudo ufw allow 1960/tcp
```

Then...

On the server for **client A**, port **1959**:
`sudo ./dsvpn server vpn.key auto 1959 auto 192.168.19.254 192.168.19.1`
On **client A** (which is a MacOSX Mojave macmini):
`sudo ./dsvpn client scaleway.key 51.15.51.45 1959 auto 192.168.19.1 192.168.19.254`

On the server for **client B**, port **1969**:
`sudo ./dsvpn server vpn.key auto 1960 auto 192.168.19.254 192.168.19.2`
On **client B** (which is an OpenBSD 6.4 10Zig thin client running as a low power server)
`doas ./dsvpn client scaleway.key 51.15.51.45 1960 tun1 192.168.19.2 192.168.19.254`

Things that works as expected:
1. I can see that the external IP is seen as the public IP of the **server** from **all** machines (through icanhazip.com)
2. I can ping both server and client B **from** client A
3. I can ping both server and client A **from** client B
4. I can connect to the outside world from all the machines
5. I can see the NGNIX instance running on the server from both client A and client B as 192.168.19.254

Things i'm currently **unable** to do:
See an httpd webserver running on client B from client A.

**Comment by jedisct1** [comment]
So close!

**Comment by Trojan295** [comment]
Points 2 and 3 would mean that you can establish a connection between A and B, as the packets are routed correctly. @microspino, can you post the result of `traceroute` and `tcptraceroute` on your NGINX port between A and B?

**Comment by microspino** [comment]
Made it! 😍😍😍 FInally!..I will update my answer with my findings.

**Comment by microspino** [comment]
> Points 2 and 3 would mean that you can establish a connection between A and B, as the packets are routed correctly. @microspino, can you post the result of `traceroute` and `tcptraceroute` on your NGINX port between A and B?

thx Damian tried and got destination unreachable after a bunch of `* * *` hops.

**Comment by jedisct1** [comment]
Thanks for the followup!

This can be very useful for many people. Maybe we should start a FAQ documenting tricks like this?

**Comment by microspino** [comment]
@jedisct1 Sure! Let me know what you want me to do.
