### ISSUE TITLE
Would you consider making releases?

### ISSUE THREAD

**Issue by nnathan** [jedisct1/dsvpn#28]
I'd like to see about getting this into homebrew. I think it meets most of the [acceptable requirements](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md), but probably needs a fixed release. You've recently added a version number, but it's not bound to any specific source code base. An alternative is to simply tag git commits with the version.

Thanks.

**Comment by jedisct1** [comment]
Yes!

I'm planning to tag the first release soon. Probably today :)

**Comment by marvinroger** [comment]
@jedisct1 Thanks for this project! I see you closed this issue, probably to keep the tracker tidy, so can you please leave a comment here once the first release is released? This way, we will be notified. 

Thanks again. 😉

**Comment by jedisct1** [comment]
First release tagged :)

**Comment by nnathan** [comment]
Looks like this probably won't get accepted so easily.

```
$ brew audit --new-formula dsvpn
dsvpn:
  * GitHub repository too new (<30 days old)
Error: 1 problem in 1 formula detected
```

In the meantime I'll keep a homebrew tap and keep up to date on releases; unless you're interested in managing your own.
[The formula can be found here](https://github.com/nnathan/homebrew-repo/blob/master/dsvpn.rb).

To install: `brew install nnathan/repo/dsvpn`.

**Comment by jedisct1** [comment]
Thanks a lot, Naveen, this is great!

Homebrew requiring an incubation period is understandable. And as long as early users can use taps, this is not a problem.

Thanks again! I'm going to add it to the documentation.
