### ISSUE TITLE
Would you consider support for client mobility?

### ISSUE THREAD

**Issue by nnathan** [jedisct1/dsvpn#29]
So wireguard supports client mobility - it's actually easy in the wireguard land because it's all UDP.

In TCP land it's a bit more difficult.

The simplest possible scenario I can think of is simply accepting multiple connections, and broadcasting all packets that are received from other networks back to the client connections.

Probably a more reliable approach is to probably prenegotiate some cookie that identifies the vpn connection and it's associated packets, and when a new connection comes in and sends the cookie over, all new packets come back to the newly established client.

In both the above, I guess there'd be some need to have some reconnection system since a transition from one network to another, I think, should close the sockets.

**Comment by jedisct1** [comment]
Hi!

Supporting mobility would add a lot of complexity, and I'd like to keep the code base simple and small as much as possible.

So, maybe as a different project, but it's a bit out of scope for dsvpn.
