### ISSUE TITLE
Reconnection does not appear to work on Linux

### ISSUE THREAD

**Issue by Vaelatern** [jedisct1/dsvpn#30]
I love this program. This seems to be unexpected behavior.

My setup: Laptop - network from an external device
dsvpn runs on my laptop.

After I unplug my network, I get
```
Unable to write data to the TCP socket: Resource temporarily unavailable
```

Then, a loop.

```
Trying to reconnect
Command [ip route show default 2>/dev/null|awk '/default/{print $3}'] failed]
Connecting to $THE_IP:$THE_PORT...
Client connection failed: Connection timed out
```

Rinse and repeat until I plug the network back in. At that point, I wait until the `Connection timed out`,  and then saw:

```
Trying to reconnect
Connecting to $THE_IP:$THE_PORT...
```

I waited for over a minute without a connection being made.

Then I control C twice, and rerun the program. It connects quickly without complaint, perfectly.
```
Interface: [tun0]
Trying to reconnect
Connecting to $THE_IP:$THE_PORT...
net.ipv4.tcp_congestion_control = bbr
Connected
```

Ideal behavior: at least after the connection attempt doomed to fail finally fails, the connection would succeed. I appreciate the unnecessary added complexity of reconnecting the moment it is possible, and wish only for an eventual link.

Thank you for this!

**Comment by jedisct1** [comment]
Reconnection when using an unstable WiFi network on MacOS seem to work fine. But I can't easily test other configurations especially with other operating systems as a client.

Maybe whatever manages the network reconfiguration on a status change gets confused by the firewall rules that still redirect all the traffic to the tunnel. Individual distributions may also manage this in their own way.

I can shoot in the dark, but that's something that could really be contributed by people actually using these environments.

**Comment by Vaelatern** [comment]
I'm running on Void Linux, and can replicate the problem reliably. If you give me something to run to debug, I can do that.

**Comment by jedisct1** [comment]
I don't think tracing the `dsvpn` code is going to help much. It's probably more about understanding how the network and firewall settings change around the time of a network loss.

**Comment by Vaelatern** [comment]
On Linux, the route 0/1 is added at application startup, and apparently removed by the OS when tun0 is destroyed.

When I removed just that route manually, dsvpn's reconnection worked, but the 0/1 route was not recreated.

**Comment by jedisct1** [comment]
This route, as well as the other `/1` are expected. If they were removed, traffic would constantly leak with an unstable connection.

But there is another more specific route to the VPN server. Check if that one sticks after a disconnection.

If it doesn't, try to find why. Maybe this is a flag that can be changed with the `ip` command?

**Comment by Vaelatern** [comment]
The specific route to the VPN host is created on VPN startup, but destroyed when the interface used is removed.
