### ISSUE TITLE
RFE: Add  TLS Server Name Indication 

### ISSUE THREAD

**Issue by git001** [jedisct1/dsvpn#35]
Do you plan to add [Server Name Indication](https://tools.ietf.org/html/rfc6066#page-6) to be able to run DSVPN server in conjunction with "normal" TLS Server?

This makes it possible to use a normal TLS Router/Loadbalancer for routing the traffic.

(RFE = Request for enhancement)

**Comment by jedisct1** [comment]
Hi!

This is very unlikely since dsvpn doesn’t use TLS at all 😀
