### ISSUE TITLE
Illegal instruction error when executing on RaspberryPi Zero

### ISSUE THREAD

**Issue by iotmani** [jedisct1/dsvpn#41]
Hello,

On PiZero (armv61), it compiles fine but fails during server execution:

$ env OPTFLAGS=-mfpu=neon make
cc -march=native -Ofast -Wall -W -Wshadow -Wmissing-prototypes -mfpu=neon -Iinclude -o dsvpn src/vpn.c src/charm.c src/os.c
strip dsvpn

I tried with different parameters (default port etc) but I get the same error:

$ sudo ./dsvpn server vpn.key auto 1959
Illegal instruction

Thanks,
IO.

**Comment by iotmani** [comment]
Nevermind, I neon is armv7, changing that to `vfpv2` for armv6 does the trick.
I'll open a PR to clarify pi 1 and zero instructions.

**Comment by jedisct1** [comment]
Yes, on Raspberry Pi Zero, you should just type `make`.

**Comment by iotmani** [comment]
Yes, I first tried setting `-mfpu=auto` but that didn't work. 
I've validated it, just `make` works perfectly fine.

Thanks for the info and for your efforts!
