### ISSUE TITLE
doesn't compile on debian

### ISSUE THREAD

**Issue by mimoo** [jedisct1/dsvpn#43]
Thanks for this!

I might not have time to investigate, so just copy/pasting the error I'm getting:

```
cc -march=native -Ofast -Wall -W -Wshadow -Wmissing-prototypes  -Iinclude -o dsvpn src/vpn.c src/charm.c src/os.c
src/charm.c: In function ‘uc_randombytes_buf’:
src/charm.c:329:26: error: ‘SYS_getrandom’ undeclared (first use in this function)
     if ((size_t) syscall(SYS_getrandom, buf, (int) len, 0) != len) {
                          ^
src/charm.c:329:26: note: each undeclared identifier is reported only once for each function it appears in
Makefile:7: recipe for target 'dsvpn' failed
make: *** [dsvpn] Error 1
```

**Comment by mimoo** [comment]
Looks like debian jessie does not provide getrandom

**Comment by jedisct1** [comment]
See https://github.com/jedisct1/dsvpn/issues/22

The software Debian Jessie comes with is very old.

**Comment by mimoo** [comment]
I realized that I really needed to update :D 

On stretch I get `-1` when calling `syscall(SYS_getrandom, buf, (int) len, 0);`. Mmmm

**Comment by jedisct1** [comment]
What do you get in `errno`?

**Comment by mimoo** [comment]
is there a way to analyze `errno` without modifying the code? I had to modify it and include `errno.h` to do that:

```
Value of errno: 38
Error printed by perror: Function not implemented
```

**Comment by jedisct1** [comment]
> is there a way to analyze errno without modifying the code?

You can use the `strace` command.
