### ISSUE TITLE
plain-text key, stuck ssh connection and up voting for multi-client support 

### ISSUE THREAD

**Issue by Grabber** [jedisct1/dsvpn#44]
**dsvpn** core concept is fantastic, thank you so much for coding and sharing it! 

My use case is to expose some local servers to a public domain name over one Amazon lightsail instance with DNS pointing to the domain.

1. if you connect to the remote instance over SSH to setup dsvpn server, as soon as you run it the SSH connection get stuck. Is it because any of the routing rules?

2. is it possible to support plain-text .key? It makes much easier to share the key between local and remote machines by just copying and pasting without having to transfer files or SSH, SFTP or HTTP.

- one up vote for multi-client support;

**Comment by jedisct1** [comment]
Hi!

The server doesn't change routing rules, but adds firewall fowarding rules as soon as it starts. I'm not sure why this is blocking your current SSH session and this is something I've never seen. Maybe you already have some firewalling rules in place and that resets their states?

It's very easy to get a printable version of the key, for example:

```sh
base64 < vpn.key
```

And to import a key from such a printable string:

```sh
echo 'Nch98/th3lQAtxDw+Jpg3AxjE4nCfUy0mkJtuV7WR0k=' | base64 -d > vpn.key
```

Multiple clients can already log in simultaneously, if they have their own TCP port. It's totally fine to run multiple instances of dsvpn server simultaneously. And if the client IPs are on the same subnet, they will be able to see each other.

**Comment by Grabber** [comment]
> Hi!
> 
> The server doesn't change routing rules, but adds firewall fowarding rules as soon as it starts. I'm not sure why this is blocking your current SSH session and this is something I've never seen. Maybe you already have some firewalling rules in place and that resets their states?

I'm checking it!

> 
> It's very easy to get a printable version of the key, for example:
> 
> ```shell
> base64 < vpn.key
> ```
> 
> And to import a key from such a printable string:
> 
> ```shell
> echo 'Nch98/th3lQAtxDw+Jpg3AxjE4nCfUy0mkJtuV7WR0k=' | base64 -d > vpn.key
> ```

What do you think about using the base64 shape instead the binary file? Or suggestion is to also support passing the priv key via a command line parameter. 

> 
> Multiple clients can already log in simultaneously, if they have their own TCP port. It's totally fine to run multiple instances of dsvpn server simultaneously. And if the client IPs are on the same subnet, they will be able to see each other.

Do you plan to embed multi-client support using a multiplexer-like approach?

**Comment by jedisct1** [comment]
Using base64 is very easy, see the commands above. So it's probably not worth reimplementing this in the VPN itself. A correct base64 implementation adds a lot of code.

The secret key as a command-line parameter is not a good idea because a copy of it will be permanently recorded to disk in your shell history. If there are other users on your system, they will also be able to see the secret key in the process list.

Multi-client support on a single port might be added at some point, but this is not something I need. Maybe if an iOS client exists, so that the phone and the laptop can be used simultaneously.

**Comment by Grabber** [comment]
> Using base64 is very easy, see the commands above. So it's probably not worth reimplementing this in the VPN itself. A correct base64 implementation adds a lot of code.
> 
> The secret key as a command-line parameter is not a good idea because a copy of it will be permanently recorded to disk in your shell history. If there are other users on your system, they will also be able to see the secret key in the process list.
> 

Ok.

> Multi-client support on a single port might be added at some point, but this is not something I need. Maybe if an iOS client exists, so that the phone and the laptop can be used simultaneously.

managing multiple server instances is boring.

**Comment by jedisct1** [comment]
So is spending time on features that makes the code more difficult to maintain, and that I don’t need.

But you are welcome to fork it and implement what you need. That is not boring :)
