### ISSUE TITLE
Different endianness causing "Authentication failed"

### ISSUE THREAD

**Issue by nalzok** [jedisct1/dsvpn#48]
I got bunch of **Authentication failed** when trying to transfer the secret key between the server and the client. After some investigation, I figured out that the machines have difference endianness.

On OpenBSD host

```bash
bash-5.0$ hexdump vpn.key
0000000    af1c    d078    16e9    5a70    9992    e795    0d09    ea70
0000010    5038    9931    7db4    049a    0385    a78e    7f32    7c97
0000020
```

On macOS client

```bash
$ hexdump vpn.key
0000000 1c af 78 d0 e9 16 70 5a 92 99 95 e7 09 0d 70 ea
0000010 38 50 31 99 b4 7d 9a 04 85 03 8e a7 32 7f 97 7c
0000020
```

Any thoughts?

**Comment by jedisct1** [comment]
Looks like that has nothing to do with the app itself, rather how you copied a file from one host to another.

How did you copy the key?

**Comment by jedisct1** [comment]
Also, these files look the same, it's just different versions of `hexdump`

**Comment by nalzok** [comment]
@jedisct1 I executed the same command on both platform. (On macOS, I changed `base64 -d` to `base64 -D`, but that shouldn't make a difference)

```
echo 'HK940OkWcFqSmZXnCQ1w6jhQMZm0fZoEhQOOpzJ/l3w=' | base64 -d > vpn.key
``` 

Both `hexdump -C` and `md5` indicate that their content is identical, and `python2 -c "import sys; print(sys.byteorder)"` confirms both systems are little endianness, so I think you are right.

Do you know how to fix the "Authentication failed" problem? I'm lost at this point. :/

**Comment by jedisct1** [comment]
Yes, it should work fine no matter what endianess the CPU uses. I just tried on a Power7 CPU and the key exchange passed.

Ok, so `Authentication failed` is not displayed while transfering the key, but when starting `dsvpn` as a client, right?

Is it the same version on both sides? If you changed the key, did you restart the server?

**Comment by jedisct1** [comment]
Do you see `authentication failed` on both sides at the same time? Both on the client *and* the server?

**Comment by nalzok** [comment]
When I run dsvpn on both client and server, client shows:

```
$ sudo ./dsvpn client vpn.key XXX.XXX.XXX.XXX 1959
Interface: [utun2]
Trying to reconnect
Connecting to XXX.XXX.XXX.XXX:1959...
Client connection failed: Connection refused
Trying to reconnect
Connecting to XXX.XXX.XXX.XXX:1959...
Client connection failed: Connection refused
Trying to reconnect
```

while server shows the following starting message without reporting any error

```
bash-5.0$ doas ./dsvpn server vpn.key auto 1959
Interface: [tun0]
net.inet.ip.forwarding: 1 -> 1

Add the following rule to /etc/pf.conf:
pass out from 192.168.192.1 nat-to egress

Listening to *:1959
```

The `Connection refused` error on client appears to have something to do with the firewall, which doesn't seem to be activated on the server

```
bash-5.0$ doas pfctl -d
pfctl: pf not enabled
```

Anyway, l just switched to port 80, and started getting `Authentication failed` on client instead.

```
Connecting to XXX.XXX.XXX.XXX:80...
Authentication failed
Trying to reconnect
Connecting to XXX.XXX.XXX.XXX:80...
Authentication failed
Trying to reconnect
```

The server still doesn't produce any error message after `Listening to *:80`.

I'm using the latest `master` branch on both client and server. I didn't change the key. It's the first time I try to set up dsvpn on this server.

**Comment by jedisct1** [comment]
Can you connect to the server IP with a web browser?

**Comment by jedisct1** [comment]
If you can’t connect to port 1959, there’s probably a firewall issue, but it may be on your router or the server’s router.

**Comment by nalzok** [comment]
@jedisct1 I can connect to port 80 on Safari, which seems to be one of the ports opened by default. I need to inquiry the support team about how to allow an arbitrary port on the server.

However, the choice of port shouldn't have anything to do with the `Authentication failed` error. I mean, the error probably won't magically disappear once I switch to port 1959, right?

**Comment by jedisct1** [comment]
Actually, you should not be able to connect with Safari since this is not a web service. It doesn’t respond to HTTP queries.

So, there is something that’s not dsvpn listening to port 80, or there is a transparent proxy on your network redirecting traffic for port 80 somewhere else.

What about the default port, port 443?

**Comment by nalzok** [comment]
@jedisct1 I just did a `nmap` and it told me port 443 is closed either.

Now I suspect that I'm not allowed to use any outgoing port on the server, since all such ports have been occupied by some service run by the host machine (and I'm working on a hosted virtual machine). From the very beginning, dsvpn should not be able to bind to port 80, as it is already used by Nginx, but somehow it is tricked into believing it can and thus didn't emit an error.

I'm going to contact the support about this issue, and see if they can get me an outgoing port. Thanks for your time!

**Comment by luckypoem** [comment]
i also got the same error.
my vps is openvz vps,i enabled tun/tap in vps control panel.

i installed this dsvpn in another vps- kvm vps,in this case ,i didn't encounter any error.

@nalzok ,is ur vps also openvz vps?
