### ISSUE TITLE
It's perfect, but doesn't work

### ISSUE THREAD

**Issue by lucasrhb** [jedisct1/dsvpn#49]
Compiled OK, started, listening on port but when connection attempt is made from client, it just sayin "Aborted" and server is no longer working.

**Client: MacOS 10.14.5**
Connecting to xxx.xxx.xxx.xxx:1959...
Client connection failed: Connection refused

**Server: Lunux Debian**
dsvpn# ./dsvpn server vpn.key auto 1959
Interface: [tun0]
net.ipv4.ip_forward = 1
RTNETLINK answers: Invalid argument
Listening to *:1959
Accepting new client from [yyy.yyy.yyy.yyy]
Aborted

**Comment by jedisct1** [comment]
Your kernel is too old.

Obsolete operating systems are not supported, sorry.

**Comment by jedisct1** [comment]
Minimum kernel version is 3.17, that was released in 2014.
