### ISSUE TITLE
No connectivity

### ISSUE THREAD

**Issue by michbsd** [jedisct1/dsvpn#52]
Server: FreeBSD
Client : Mac (darwin) 

The client says connected:
Interface: [utun3]
Trying to reconnect
Connecting to X.X.X.X:8080...
add host X.X.X.X: gateway 192.168.1.1
add net 0: gateway 192.168.192.254
add net 128: gateway 192.168.192.254
add net 0000::/1: gateway 64:ff9b::192.168.192.254
add net 8000::/1: gateway 64:ff9b::192.168.192.254
Connected

However in the server log it says: 
net.inet.ip.forwarding: 1 -> 1
Authentication failed
Accepting a new client failed: Permission denied

I can ping/ssh to the server on the local int (192.168.192.254)

However, nothing else is working (8.8.8.8, 1.1.1.1 etc etc) 

No firewall on server, and no firewall on my mac.

Any ideas ?

**Comment by jedisct1** [comment]
As documented, FreeBSD is only supported as a client and in point-to-point mode. On FreeBSD, `dsvpn` doesn't add any firewall/nat rules because I don't use FreeBSD and have no idea how to do this :) But feel free to add the relevant bits to `src/os.h` is you know how to do it.

**Comment by michbsd** [comment]
OK thanks!

**Comment by Fastidious** [comment]
> But feel free to add the relevant bits to `src/os.h` is you know how to do it.

That should be `src/os.c`.
