### ISSUE TITLE
Do we expect an Ubuntu 18.04.x client to work?

### ISSUE THREAD

**Issue by johnnyutahh** [jedisct1/dsvpn#54]
Do we expect an Ubuntu 18.04.x client to work?

It does not for me. I run the following...

```
root@node111 Sep 09 19:03:15 /root# ./dsvpn.bin.ubuntu-18.04.2 client 2019-09-08-dsvpn.key node113.xxx.tld 2001
Interface: [tun0]
```

...and it hangs _all_ (possibly?) network interfaces - or at least, my DigitalOcean (DO) instance's sshd ceases to respond, and the only way I know thus far to get it (node111) is to power-cycle it from DO's control panel web page.

Again, this problematic behavior is only for client-side operations.

The same DO VPS above, when running as a dsvpn server, seems to server a macOS client fine. Same for node113 (who is attempting to server node111 as a client) to the same macOS client.

**Comment by johnnyutahh** [comment]
The server side:

```
root@node113 Sep 09 19:02:07 /root# ./dsvpn.bin.ubuntu-18.04.2 server 2019-09-08-dsvpn.key auto 2001
Interface: [tun0]
net.ipv4.ip_forward = 1
Listening to *:2001
```

The version:

```
root@node113 Sep 09 19:28:50 /root# ./dsvpn.bin.ubuntu-18.04.2 
DSVPN 0.1.3 usage:

dsvpn	"server"
	<key file>
	<vpn server ip or name>|"auto"
	<vpn server port>|"auto"
	<tun interface>|"auto"
	<local tun ip>|"auto"
	<remote tun ip>"auto"
	<external ip>|"auto"

dsvpn	"client"
	<key file>
	<vpn server ip or name>
	<vpn server port>|"auto"
	<tun interface>|"auto"
	<local tun ip>|"auto"
	<remote tun ip>|"auto"
	<gateway ip>"auto"

root@node113 Sep 09 19:28:54 /root# 
```

**Comment by jedisct1** [comment]
I've never tried on a Linux distribution that old, but if it compiles and starts, it's probably fine.

If you are starting `dsvpn` as a client, all the traffic is now being routed to the server. So it's expected that you can't connect to that host's regular IP address any more. It won't send anything directly to the Internet, everything goes to the tunnel.

You can connect to it from the *server* using its VPN IP address (`192.168.100.1` by default).

**Comment by johnnyutahh** [comment]
Thanks. In some cases (like this one), I want to keep the existing (at the time of the 'dsvpn client' run) network interfaces still functioning (directly to the Internet, as you put it) as they were before. I only want the routes to the server to be "secure tunneled"--if I'm using that terminology correctly.

Is there a means to do that with dsvpn?

The purpose: think of "the client" in this case as a laptop and the server is a VPS on the public Internet running several apps/services available to said laptop and only said laptop -- and want to employ the VPN solely for the point of minimizing the VPS's exposure to the public internet. We are NOT trying to route all the laptop's traffic through the server; rather, we are simply trying to protect the server from unnecessary Internet exposure (so we don't have to properly secure it with updated patches for its httpd and sshd and similar processes).

Does my explanation make sense?

**Comment by jedisct1** [comment]
If you check out the current code in git, you can compile with:

`env OPTFLAGS=-DNO_DEFAULT_ROUTES make`

to avoid installing the routes.
