### ISSUE TITLE
GFW certificated

### ISSUE THREAD

**Issue by cattyhouse** [jedisct1/dsvpn#59]
very nice little program, tested server on Debian10  and client on macOS, worked great, it even adds routes and MASQUERADE automatically!

but it is already GFW (you may heard of it, if not,  it stands for Great Fire Wall) certificated, several mins later, disconnected and not able to connect again. Anyway, thanks for this great program.

**Comment by jedisct1** [comment]
Even on port 443?

**Comment by cattyhouse** [comment]
> Even on port 443?
Sorry due to my complex network setup, i forgot to reset my router DHCP settings to default, the information i provided was not accurate, it is actually GFW resistance at the moment.  I will test for few days see if GFW bother me or not. I'm sorry.

**Comment by testcaoy7** [comment]
@cattyhouse How to compile dsvpn under macOS ?

**Comment by briteming** [comment]
@jedisct1 
hi,
in my linux vps,i run:
./dsvpn server vpn.key auto 1959

do i have to use port 443 in order to encrypt the connection?

**Comment by briteming** [comment]
@cattyhouse 
hi,
你在服务器上，让dsvpn监听443端口，就一直能使用dsvpn而未导致你服务器的ip被封吗？
我先头让dsvpn监听1959端口，导致我的vps两次被封IP。
谢谢回复

**Comment by briteming** [comment]
在服务器上，让dsvpn监听443端口,暂时能翻墙，看看 能维持多久，也许forever?
