### ISSUE TITLE
cdn support

### ISSUE THREAD

**Issue by cute** [jedisct1/dsvpn#64]
If you want to use a CDN service, such as Cloudflare. The request needs to be disguised as an HTTP request. for example:

client exchange key request:

```
GET / HTTP/1.1\r\n
Host: example.com\r\n
User-Agent: foobar/1.0\r\n
Upgrade: websocket\r\n
Connection: Upgrade\r\n
Sec-WebSocket-Key: base64-key\r\n\r\n
```

server exchange key response:
```
HTTP/1.1 101 Switching Protocols\r\n
Server: nginx/1.0\r\n
Date: Mon, 11 Nov 2019 12:48:23 GMT\r\n
Upgrade: websocket\r\n
Connection: Upgrade\r\n
Sec-WebSocket-Accept: base64-key\r\n\r\n
```

**Comment by jedisct1** [comment]
Hi,

I don't really have any need for this, and it would be better to keep `dsvpn` small and simple rather than add a HTTP layer into it.

But feel free to maintain a version with such a feature if you need it!

**Comment by jedisct1** [comment]
Looks like this may be very useful to people in China, so I'm going to try to implement this after all.
But probably in a different branch.

**Comment by jedisct1** [comment]
The `websocket` branch implements this, but I didn't try over a CDN.

**Comment by jedisct1** [comment]
Merged to `master`.

A little bit raw, and it probably doesn't if the CDN alters headers, but I am currently using it over Cloudflare, and it seems to work.

**Comment by jedisct1** [comment]
I'm not too happy with the current interface though. It requires a lot of extra `auto` on the command-line.

Maybe the protocol should be changed to always do that, but that would be a breaking change, and it would be best to keep backward compatibility.

Any suggestion on how to improve this? Maybe use `wsclient` and `wsserver` instead of `client` and `server` (first argument on the command line)?

**Comment by jedisct1** [comment]
My bad. It doesn't work over Cloudflare.

**Comment by jedisct1** [comment]
This is due to the extra headers they add. We need to parse headers in a slightly more complicated way.

**Comment by jedisct1** [comment]
Looks like we need a bit more than just headers, since we also need to use proper frames, and send ping/pong to keep the connection alive.

So, that would be a different project.
