### ISSUE TITLE
Can I use this over Wireguard, and just tunnel UDP traffic over it?

### ISSUE THREAD

**Issue by Marctraider** [jedisct1/dsvpn#71]
Using Wireguard for a redundant setup right now (all packets get duplicated) basically my whole internet goes through it. But for reasons (Proper packet sequence, packet order, out of order) i want to tunnel my network-wide udp packets over DSVPN that runs over the wireguard tunnel.

So basically Internal network UDP packets -> DSVPN -> Wireguard -> DSVPN -> UDP.

How does dsvpn work with routes, you describe that it works out of the box so it already touches routes and stuff itself?

Edit: Mhh, If NO_DEFAULT_ROUTES has been defined, default routes will not be installed. Guess that helps!

**Comment by jedisct1** [comment]
Haha, you beat me to it :)

Yes, compiling with `NO_DEFAULT_ROUTES` will enable the VPN interface without setting up the routes.

So, redirecting only UDP traffic to that interface definitely looks doable. I'm not familiar enough with Linux to know the exact `ip route` and `nft` commands to do it, but it shouldn't be too difficult to find.

**Comment by Marctraider** [comment]
Thanks!

I got dsvpn tunnel working over redundant wireguard tunnel (1440 mtu)

Just curious what mtu i should set for tun0, i.e. what is the overhead?

Thx!

**Comment by jedisct1** [comment]
Overhead per packet is 18 bytes.
