### ISSUE TITLE
about clang-format

### ISSUE THREAD

**Issue by kongsys** [jedisct1/dsvpn#74]
hello, i have a question, i saw clang-format in your repo, this file for IDE? what code tool do you use. i am sorry, this question not about dsvpn, i am beginner, i am use emacs as ide, but it too complex, too more config.

**Comment by jedisct1** [comment]
Hi!

I use VSCode. It is very easy to configure, basically just install the extensions you want for the language you use. For C I just use the C++ Intellisense extesion.

`clang-format` is part of LLVM and can work anywhere, including from the command-line, but VSCode will call it automatically if you install the `clang-format` extension.
