### ISSUE TITLE
Optional encryption

### ISSUE THREAD

**Issue by jayanta525** [jedisct1/dsvpn#76]
Not an issue but a question regarding encryption performance.

Been using DSVPN on OpenWrt, with everything configured and working fine. But due to encryption the max speed is limited at just 30Mbps, on a cortexA7 1.2Ghz board.

Is there any way to disable encryption and establish a tunnel? My other alternatives were, gre,pptp,etc, but dsvpn seems to work perfectly with mptcp.

**Comment by jedisct1** [comment]
Sorry, there are no ways to disable encryption.
