### ISSUE TITLE
Make Error on ubuntu

### ISSUE THREAD

**Issue by BlueWaterCrystal** [jedisct1/dsvpn#78]
Git clone and release version 1.4.0 fail to make on ubuntu x86_64

`cc $(cat ".cflags")  -Iinclude -o dsvpn src/vpn.c src/charm.c src/os.c
cc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
src/charm.c: In function ‘uc_randombytes_buf’:
src/charm.c:331:26: error: ‘SYS_getrandom’ undeclared (first use in this function)
     if ((size_t) syscall(SYS_getrandom, buf, (int) len, 0) != len) {
                          ^
src/charm.c:331:26: note: each undeclared identifier is reported only once for each function it appears in
src/charm.c: At top level:
cc1: warning: unrecognized command line option "-Wno-unused-command-line-argument" [enabled by default]
make: *** [dsvpn] Error 1
`

**Comment by jedisct1** [comment]
What version of Ubuntu is that?

**Comment by BlueWaterCrystal** [comment]
Fixed by upgrading Ubuntu from 14.04 to latest version

**Comment by jedisct1** [comment]
Ubuntu 14.04 reached end of life in April 2019. It doesn't receive any support or updates (including security) any more.

So if you still have boxes running this, upgrading is definitely not a bad idea.
