### ISSUE TITLE
Ability to save to a configuration file, etc.

### ISSUE THREAD

**Issue by Fastidious** [jedisct1/dsvpn#8]
Will it be possible to add the ability to save all settings to a configuration file? That way we could simply call `dsvpn --config /path/to/config` on both, server and client—this is in addition of being able to use it as it is done today.

Along the line to make it simpler, would it be possible to autodetect the external gateway, and interface, so they don't have to be entered?

**Comment by jedisct1** [comment]
The external interface is only required on the server, so you only need it once.

Here's a script the start the client. The gateway will be filled automatically:

```sh
dsvpn client \
  vpn.key \
  auto \
  192.168.192.1 192.168.192.254 \
  your.vpn.server.ip 443 \
  auto \
  $(netstat -rn | awk '/default/{if(index($6,"en")){print $2}}')
```

on Linux, replace the last line with `ip route show default|awk '/default/{print $3}'`.

As you can see, it's not any longer than a configuration file and offers more flexibility.

On the server, the external interface can be returned by `ip route show default|awk '{print $3}'`.

So a server script can just be:

```sh
dsvpn server \
  vpn.key \
  auto \
  192.168.192.254 192.168.192.1 \
  auto 443 \
  $(ip route show default|awk '{print $5}') \
  auto
```

Hope it helps.

**Comment by jedisct1** [comment]
Ok, no need for this after all.

Look at the updated documentation. Some breaking changes have been made, but I think it couldn't be any easier at that point :)

**Comment by Fastidious** [comment]
> Some breaking changes have been made, but I think it couldn't be any easier at that point :)

Woah, that's perfect! Really love `dsvpn`, thanks!

**Comment by Fastidious** [comment]
@jedisct1 it is dumping a core when ran as `dsvpn server vpn.key auto 4443` on server. I can't, for the life of me, find the core file. Running in on Ubuntu 18.04.1.

**Comment by jedisct1** [comment]
Can you check that you have the very last version from git, and that you recompiled that one?

**Comment by Fastidious** [comment]
I did it right after you commented, yes. Let me recompile, and post back.

**Comment by Fastidious** [comment]
OK, no dump file now. I am now getting:
```
root@vm:/usr/local/bin# dsvpn server vpn.key 4443
Interface: [tun0]
net.ipv4.ip_forward = 1
tcp_listener: Address already in use
```
No matter what port I enter.

**Comment by jedisct1** [comment]
Means that there is already an instance running, and listening to the same port :)

**Comment by Fastidious** [comment]
@jedisct1 that's what I thought too. Looked for it, there was none. To be absolute sure, I rebooted the box. Still the same.

**Comment by Fastidious** [comment]
@jedisct1 tried on different server. Got something new:
```
root@vm2:/usr/local/bin# dsvpn server vpn.key 4443
Interface: [tun0]
net.ipv4.ip_forward = 1
Listening to 4443:443
tcp_listener: Address already in use
```

**Comment by jedisct1** [comment]
` dsvpn server vpn.key 4443`

That should be

` dsvpn server vpn.key auto 4443`

**Comment by jedisct1** [comment]
The IP should be before the port (or `auto`).

It's not really required on the server, but it's to be consistent with the command line used on the client.

**Comment by Fastidious** [comment]
@jedisct1 duh! Back to seg fault, and core.

**Comment by jedisct1** [comment]
Damn.

Unfortunately I'm not able to reproduce this.

Can you `gdb` it to see where's it's segfaulting?

**Comment by jedisct1** [comment]
Does `ip route show default|awk '/default/{print $5}'` return the interface?

**Comment by Fastidious** [comment]
> Does ip route show default|awk '/default/{print $5}' return the interface?

Yes, it returns the interface. How do I go by using `gdb`?

**Comment by Fastidious** [comment]
OK, ran `gdb`:
```
(gdb) run server vpn.key auto 4443
Starting program: /usr/local/bin/dsvpn server vpn.key auto 4443
Interface: [tun0]

Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
```

**Comment by Fastidious** [comment]
@jedisct1 on a different server:
```
(gdb) run server vpn.key auto 4443
Starting program: /usr/local/bin/dsvpn server vpn.key auto 4443
Interface: [tun0]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b725a1 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by jedisct1** [comment]
Now type `bt` to get a backtrace.

**Comment by Fastidious** [comment]
If you get me your SSH pub key, I can grant you access to one of those boxes.

**Comment by jedisct1** [comment]
`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICOrqHmGXBNb9r/ozIAm5uyxkpLZflkke4uX2f4sZJs9 j@mincore`

**Comment by Fastidious** [comment]
@jedisct1 hit `bar.quark.rocks` with `david` on `22`.

**Comment by jedisct1** [comment]
Ok, should be fixed, thanks! Try the current code.

**Comment by jedisct1** [comment]
And thanks a ton for the SSH access. That was invaluable in order to quickly spot the bug!

**Comment by Fastidious** [comment]
@jedisct1 you are welcome, and thanks, it works! :-) Cheers!
