### ISSUE TITLE
Client-Server connectivity only

### ISSUE THREAD

**Issue by Fastidious** [jedisct1/dsvpn#9]
Running commit 8ffd8e1. At work, I can connect to server, and communication between server and client (running macOS Mojave) works, but Internet access is lost. Work setup might not be the best to test this, so will try from home and report the behaviour.

**Comment by jedisct1** [comment]
The client is supposed to add routes to redirect all the traffic to the VPN:

```sh
0/1                192.168.192.254    UGSc          111        0   utun5
128.0/1            192.168.192.254    UGSc           17        0   utun5
```

(`192.168.192.254` is the tunnel IP of the server)

+ the IPv6 counterparts

**Comment by Fastidious** [comment]
This shows on the client:
```
dreadnought:bin david$ netstat -rn |grep 192.168.192.254
0/1                192.168.192.254    UGSc           86        0   utun2
128.0/1            192.168.192.254    UGSc            0        0   utun2
192.168.192.254    192.168.192.1      UHr             8       10   utun2
```

**Comment by jedisct1** [comment]
I don't know, sorry :(

Maybe there are firewall rules on this laptop preventing you from using different routes?

**Comment by Fastidious** [comment]
@jedisct1 I will try from home and report back. This is an iMac, no firewall rules.

**Comment by Fastidious** [comment]
@jedisct1 this works fine from home. It has to be some enterprise firewall in place at work blocking the traffic, or something of that nature.
