### ISSUE TITLE
Accepting a new client failed (Clock difference is too large)

### ISSUE THREAD

**Issue by fqqf** [jedisct1/dsvpn#92]
![image](https://user-images.githubusercontent.com/77983090/189654624-e9242289-3a8e-4495-9c38-c0772776b5c0.png)

**Comment by fqqf** [comment]
Nvm, builded it without this check

**Comment by jedisct1** [comment]
The error message means that the clock of the client or the clock of the server are not properly set.

Removing the check is not a good idea. You should properly set your system clock instead.

**Comment by fqqf** [comment]
Thank you for reply! Sadly i can not change that since server and client must be bind to two separate NTP servers

**Comment by jedisct1** [comment]
But the tolerance is 2 hours!

If both are using NTP servers, even different ones, one of these NTP servers must be completely off.
