### ISSUE TITLE
tun device creation: No such file or directory

### ISSUE THREAD

**Issue by yonas** [jedisct1/dsvpn#99]
```
$ doas dsvpn client vpn.key myserver.lan  auto 1959                                                                                                                                                                    
tun device creation: No such file or directory      
```

dsvpn: 0.1.4
FreeBSD 14.0-RELEASE

**Comment by yonas** [comment]
The client connects fine when run from Linux (Ubuntu).

**Comment by jedisct1** [comment]
I don't use FreeBSD, but according to some basic search on Google, `tun` doesn't work in FreeBSD jails.

**Comment by yonas** [comment]
@jedisct1 I'm testing this outside jails.

**Comment by jedisct1** [comment]
Unfortunately I won't be able to help.

If the port doesn't work any more, or if the instructions are incorrect, you should report it to the port maintainer instead.

**Comment by yonas** [comment]
@jedisct1 Thanks, I've posted a on FreeBSD bugs here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275342
